meeteat/meetandeat/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import *

app_name = 'meetandeat'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('event/<int:pk>/', EventDetailView.as_view(), name='event-view'),
    path('event/<int:pk>/join', EventJoinView.as_view(), name='join-event'),
    path('event/<int:pk>/leave', EventLeave.as_view(), name='leave-event'),
    path('event/<int:pk>/report', EventReport.as_view(), name='report-event'),
    path('event/create/', EventCreate.as_view(), name='create-event'),
    path('event/<int:pk>/edit/', EventUpdate.as_view(), name='edit-event'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html',
                                                authentication_form=LoginForm, redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('my_events/', OwnEventsView.as_view(), name='own_events_list'),
    path('profile/edit', UserUpdateView.as_view(), name='edit-profile'),
    path('profile/delete-ajax', UserDeleteAjax.as_view(), name='delete-profile-ajax'),
    path('profile/delete', UserDeleteView.as_view(), name='delete-profile'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('activate_account/<str:uidb64>/<str:token>', UserActivateAccountView.as_view(), name='activate-account'),
    path('request_activation', RequestActivateAccountView.as_view(), name='request-activation'),
    path('request_email_confirm', RequestEmailConfirmView.as_view(), name='request-email-confirm'),
    path('password_reset/request', RequestPasswordResetView.as_view(), name='password-reset-request'),
    path('password_reset/confirm/<str:uidb64>/<str:token>',
         PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('mod/dashboard', ModView.as_view(), name='modView'),
    path('mod/hide/<int:pk>/', ModHide.as_view(), name='modHide'),
    path('mod/unreport/<int:pk>/', ModUnReport.as_view(), name='modUnreport'),
    path('tag/create/', TagCreate.as_view(), name='create-tag'),
    path('mod/tag/<int:pk>/', TagDetailView.as_view(), name='tag-details'),
    path('mod/tag/<int:pk>/edit/', TagUpdate.as_view(), name='edit-tag'),
    path('mod/tag/<int:pk>/approve/', ApproveTag.as_view(), name='approve-tag'),
    path('mod/tag/all/', TagView.as_view(), name='tag-view'),
    path('tags/', NotificationView.as_view(), name='NotificationView'),
    url(r'^ajax/event_get_comments/$', event_get_comments, name='comments_changed'),
]

meeteat/meeteat/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meetandeat.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meeteat/meetandeat/models.py
from datetime import timedelta
import datetime
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone




# Create your models here.

class Event(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=40)
    description = models.CharField(max_length=160)
    location = models.CharField(max_length=30)
    date = models.DateField(default=timezone.now)
    time = models.TimeField(default=timezone.now)
    visible = models.BooleanField(default=True)
    participants_number = models.IntegerField(default=2, validators=[MaxValueValidator(16), MinValueValidator(2)])
    tags = models.ManyToManyField(to='meetandeat.Tag')
    matching = models.IntegerField(default=101)

    class Meta:
        permissions = [("join_event", 'Can join event'), ("hide_event", 'Can hide event'),
                       ('edit_event', 'Can Edit Event'), ('seeHidden_event', 'Can see hidden events')]

        ordering = ['date', 'time']

    def save(self, *args, **kwargs):
        super(Event, self).save(*args, **kwargs)
        self.eventParticipants.add(self.user)

    def get_absolute_url(self):
        return reverse('meetandeat:event-view', args=[str(self.pk)])

    def hide_by_enough_reports(self):
        reportNumber = self.reports.filter(valid=None).count()
        if reportNumber >= 5:
            self.visible = False
            self.save()

    def leave(self, user):
        if user in self.eventParticipants.all():
            self.eventParticipants.remove(user)
            self.save()

    def set_matching(self, matching):
        self.matching = round(matching, 1)
        self.save()

    def is_full(self):
        print(self.eventParticipants.all().count())
        return not self.eventParticipants.count() < self.participants_number
    
    def __str__(self):
        return self.title


class Tag(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    alphabetic = RegexValidator(r'^[a-zA-Z]*$', 'Only alphabetic characters are allowed.')

    title = models.CharField(max_length=15, validators=[alphabetic])
    description = models.CharField(max_length=160, default="")
    disapprovalMsg = models.CharField(max_length=160, default="")
    approved = models.BooleanField(default=False)
    pending = models.BooleanField(default=True)

    def approve(self):
        self.approved = True

    def disapprove(self):
        self.approved = False

    def __str__(self):
        return self.title


class Report(models.Model):
    reportReason = models.TextField(blank=True, null=True)
    reporter = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='reports')
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='reports')
    valid = models.BooleanField(null=True, blank=True, default=None)


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    datetime = models.DateTimeField(default=timezone.now)
    text = models.CharField(max_length=160)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)


class User(AbstractUser):
    # TODO: create a function to name files unique
    def user_directory_path(self, filename):
        # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
        return 'user_{0}/{1}'.format(self.id, filename)

    profilePicture = models.ImageField(upload_to=user_directory_path, null=True, blank=True)
    visible = models.BooleanField(default=True)
    events = models.ManyToManyField(Event, related_name='eventParticipants', blank=True)
    # reports = models.ManyToManyField(Report, related_name='users', blank=True)
    # reportedEvents = models.ManyToManyField(Event, related_name='userReportings', blank=True)
    last_activation_attempt = models.DateTimeField(null=True, blank=True)
    activation_attempts_number = models.IntegerField(default=0)
    old_email = models.EmailField('old email address', null=True, blank=True)
    is_email_confirmed = models.BooleanField(default=False)

    def confirm_email(self):
        self.is_active = True
        self.activation_attempts_number = 0
        self.old_email = None
        self.is_email_confirmed = True
        self.last_activation_attempt = timezone.now() - timedelta(hours=1)

    def new_activation_attempt(self):
        self.last_activation_attempt = timezone.now()
        self.activation_attempts_number += 1

    def new_email(self):
        self.old_email = self.email
        self.is_email_confirmed = False

    def set_old_email(self):
        self.email = self.old_email
        self.is_email_confirmed = True

    def activation_attempt_failed(self):
        self.activation_attempts_number -= 1
        self.last_activation_attempt = timezone.now() - timedelta(hours=1)

meeteat/meetandeat/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError
from django.forms.widgets import PasswordInput, TextInput
from django_select2.forms import Select2MultipleWidget

from meetandeat.models import *


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='', widget=TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(label='',
                               widget=PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))


class RequestActivationLinkForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']

    def clean(self):
        username = self.cleaned_data.get('username')
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            raise ValidationError({'username': ["This username does not exist", ]})
        if user.activation_attempts_number >= 3:
            raise ValidationError({'username': ["You have requested too many links", ]})
        if user.last_activation_attempt is not None \
                and user.last_activation_attempt + timedelta(hours=1) > timezone.now():
            raise ValidationError({'username': ["You have requested an activation link recently", ]})


class RequestPasswordResetLinkForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']

    def clean(self):
        username = self.cleaned_data.get('username')
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            raise ValidationError({'username': ["This username does not exist", ]})


class ChangeProfilePictureForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['profilePicture', ]

    def clean_profilePicture(self):
        profilePicture = self.cleaned_data.get("profilePicture")
        file_size = profilePicture.size
        limit_mb = 8
        if profilePicture is None:
            return profilePicture
        if file_size > limit_mb * 1024 * 1024:
            raise ValidationError("Max size of file is %s MB" % limit_mb)
        return profilePicture


class CommentForm(forms.ModelForm):
    text = forms.CharField(label="text",
                           widget=forms.TextInput(attrs={'class': "form-control", 'placeholder': 'Leave your comment here', 'autocomplete': 'off'}), max_length=160)

    class Meta:
        model = Comment
        fields = ['text', ]


class DeleteProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['password', ]

    def clean_password(self):
        password = self.cleaned_data.get("password")
        if not self.instance.check_password(password):
            raise ValidationError("Entered password is not valid")
        return password


class EventForm(forms.ModelForm):
    tags_queryset = Tag.objects.filter(approved=True)
    tags = forms.ModelMultipleChoiceField(queryset=tags_queryset,
                                          widget=Select2MultipleWidget(attrs={'style': 'width: 100%;'}), required=False)

    date = forms.DateField(label="", input_formats=['%d/%m/%Y'])
    time = forms.TimeField(label="", input_formats=['%H:%M'])

    class Meta:
        model = Event
        fields = ['title',
                  'description',
                  'location',
                  'participants_number',
                  'date',
                  'time',
                  'tags']


class TagFilterForm(forms.Form):
    tags_queryset = Tag.objects.filter(approved=True)
    tags = forms.ModelMultipleChoiceField(required=False, queryset=tags_queryset,
                                          widget=Select2MultipleWidget(attrs={'style': 'width: 100%;', 'data-placeholder': 'Search by Tag', 'allowClear': True}))
    date = forms.DateField(widget=forms.DateInput(attrs={'autocomplete': 'off'}),
                           label="", input_formats=['%d/%m/%Y'], required=False)
    time = forms.TimeField(widget=forms.TimeInput(attrs={'autocomplete': 'off'}),
                           label="", input_formats=['%H:%M'], required=False)


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = [
            'title', 'description']

    def clean(self):
        title = self.cleaned_data.get('title')
        if Tag.objects.filter(title=title).exists():
            raise ValidationError("Tag already exists.")


class TagDisapprovalForm(forms.ModelForm):
    CHOICES = (
        ('Tag already exists.', 'Tag already exists.'),
        ('Tag is inappropriate.', 'Tag is inappropriate.'),
        ('Description not clear.', 'Description not clear.'),
    )
    disapprovalMsg = forms.CharField(widget=forms.Select(choices=CHOICES))

    class Meta:
        model = Tag
        fields = [
            'disapprovalMsg']


class UserRegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        # make user email field required
        self.fields['email'].required = True

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'profilePicture']

    def clean_profilePicture(self):
        profilePicture = self.cleaned_data.get("profilePicture")
        if profilePicture is None:
            return profilePicture
        file_size = profilePicture.size
        limit_mb = 8
        if file_size > limit_mb * 1024 * 1024:
            raise ValidationError("Max size of file is %s MB" % limit_mb)
        return profilePicture

meeteat/meetandeat/templates/base.html
<!doctype html>
{% load static %}
{% load settings_value %}

{% settings_value "DECOUPLE_CONFIGURATION" as environment%}

<html lang="de">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--
    Had to move this from end of body to start of header
    to make 'select2' widget for tags to work
    Maybe there is a better solution but it has to be loaded first
    -->
    <script src="{% static "meetandeat/js/jquery-3.4.1.min.js" %}"></script>

    <link rel="icon" type="image/png" href="{% static "meetandeat/icons_favicon/favicon-32x32.png" %}" sizes="32x32" />
    <link rel="icon" type="image/png" href="{% static "meetandeat/icons_favicon/favicon-16x16.png" %}" sizes="16x16" />
    <link rel="shortcut icon" href="{% static "meetandeat/icons_favicon/favicon.ico" %}">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">

    <!-- for date and time picker-->
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'meetandeat/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'meetandeat/css/global.css' %}">


    {% block css %}{% endblock css %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body class="bg-custom-primary"  id="{{ request.resolver_match.url_name }}">


    {% include "header.html" %}


    <main class="mb-3 pb-3">
        {% block main %}{% endblock %}
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- jQuery moved to head -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="{% static 'meetandeat/js/bootstrap.js' %}" type="text/javascript"></script>
    <script src="{% static 'meetandeat/js/script.js' %}" type="text/javascript"></script>


    {% block js %}{% endblock js %}
</body>
</html>

meeteat/meetandeat/templates/header.html
{% load settings_value %}
{% load static %}
{% settings_value "DECOUPLE_CONFIGURATION" as environment%}

<header class="sticky-top mb-4">

    {% if  environment == "production" %}
        <div class="warning-test-version">
            <div>
                <span class="">This is the test version of the site, all the data will be deleted until 20.07.19</span>
            </div>
        </div>
    {% endif %}
    <nav class="navbar navbar-expand-md p-3 mb-3 rounded bg-custom-secondary" style="box-shadow: #484848;">
        <a class="navbar-brand" href="{% url 'meetandeat:index' %}" style="color: #dd5549">Meet&Eat</a>
        {#for mobile version#}
        {% if user.is_authenticated %}
        <div class="d-flex order-md-1 ml-auto pr-2">
            <ul class="navbar-nav flex-row">
                <li>
                    <a href="{% url 'meetandeat:create-event' %}" class="btn btn-custom-primary">Create Event</a>
                </li>
            </ul>
        </div>
        {% endif %}
        <div class="d-none d-md-flex order-md-2 ml-auto pr-2">
            <ul class="navbar-nav flex-row">
                {% if user.is_authenticated %}
                <li >
                    <div class="btn-group dropdown" style="margin-left:15px; cursor: pointer">
                        <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle d-flex flex-row align-items-center justify-content-center"
                           data-toggle="dropdown" id="dropdownMenuLink" role="button">
                            <div class="profile-img-header-wrapper">
                                <img {% if request.user.profilePicture %}src="{{ request.user.profilePicture.url }}" {% else %}src="{% static "meetandeat/img/generic-profile-picture.jpg" %}"{% endif %} alt="" class="rounded profile-img-header" >
                            </div>
                        </a>

                        <div aria-labelledby="dropdownMenuLink" class="dropdown-menu dropdown-menu-right">
                          <a class="dropdown-item" href="{% url 'meetandeat:profile' %}">Profile{% if request.resolver_match.url_name == 'profile' %}<span class="sr-only">(current)</span>{% endif %}</a>
                          <a class="dropdown-item" href="{% url 'meetandeat:NotificationView' %}">Tags{% if request.resolver_match.url_name == 'NotificationView' %}<span class="sr-only">(current)</span>{% endif %}</a>
                          <a class="dropdown-item" href="{% url 'meetandeat:logout' %}">Logout{% if request.resolver_match.url_name == 'logout' %}<span class="sr-only">(current)</span>{% endif %}</a>
                        </div>
                    </div>
                </li>
                {% else %}
                <li class="nav-item {% if request.resolver_match.url_name == 'login' %}active{% endif %}">
                        <a class="nav-link text-custom-hyperlink" href="{% url 'meetandeat:login' %}">Login{% if request.resolver_match.url_name == 'login' %}<span class="sr-only">(current)</span>{% endif %}</a>
                </li>
                <li class="nav-item mr-auto {% if request.resolver_match.url_name == 'create-account' %}active{% endif %}">
                        <a class="nav-link text-custom-hyperlink" href="{% url 'meetandeat:register' %}">Register{% if request.resolver_match.url_name == 'register' %}<span class="sr-only">(current)</span>{% endif %}</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <span class="spacing border-right d-none d-md-inline"></span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="material-icons">menu</span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {# left floating items            #}
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                <li class="nav-item {% if request.resolver_match.url_name == 'own_events_list' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'meetandeat:own_events_list' %}">My events{% if request.resolver_match.url_name == 'own_events_list' %}<span class="sr-only">(current)</span>{% endif %}</a>
                </li>
                {% endif %}
                {% if user.is_staff %}
                <li class="nav-item {% if request.resolver_match.url_name == 'modView' %}active{% endif %}">
                    <a class="nav-link text-custom-hyperlink" href="{% url 'meetandeat:modView' %}">Mod{% if request.resolver_match.url_name == 'modView' %}<span class="sr-only">(current)</span>{% endif %}</a>
                </li>
                <li class="nav-item {% if request.resolver_match.url_name == 'tag-view' %}active{% endif %}">
                    <a class="nav-link text-custom-hyperlink" href="{% url 'meetandeat:tag-view' %}">Manage tags{% if request.resolver_match.url_name == 'tag-view' %}<span class="sr-only">(current)</span>{% endif %}</a>
                </li>
                {%endif %}

            </ul>

            {# responsive mobile menu            #}
            <ul class="navbar-nav ml-auto d-md-none">
                {% if user.is_authenticated %}
                <li class="nav-item {% if request.resolver_match.url_name == 'profile' %}active{% endif %}">

                    <a class="nav-link text-custom-hyperlink d-flex align-items-center" href="{% url 'meetandeat:profile' %}">
                        <div class="profile-img-header-wrapper mr-1">
                            <img {% if request.user.profilePicture %}src="{{ request.user.profilePicture.url }}" {% else %}src="{% static "meetandeat/img/generic-profile-picture.jpg" %}"{% endif %} alt="" class="rounded profile-img-header" >
                        </div>
                        Profile{% if request.resolver_match.url_name == 'profile' %}<span class="sr-only">(current)</span>{% endif %}</a>
                </li>
                <li class="nav-item {% if request.resolver_match.url_name == 'NotificationView' %}active{% endif %}">
                    <a class="nav-link text-custom-hyperlink" href="{% url 'meetandeat:NotificationView' %}">Tags{% if request.resolver_match.url_name == 'NotificationView' %}<span class="sr-only">(current)</span>{% endif %}</a>
               </li>
                <li class="nav-item {% if request.resolver_match.url_name == 'logout' %}active{% endif %}">
                    <a class="nav-link text-custom-hyperlink" href="{% url 'meetandeat:logout' %}">Logout{% if request.resolver_match.url_name == 'logout' %}<span class="sr-only">(current)</span>{% endif %}</a>
               </li>
                {% else %}
                <li class="nav-item {% if request.resolver_match.url_name == 'login' %}active{% endif %}">
                    <a class="nav-link text-custom-hyperlink" href="{% url 'meetandeat:login' %}">Login{% if request.resolver_match.url_name == 'login' %}<span class="sr-only">(current)</span>{% endif %}</a>
                </li>
                <li class="nav-item mr-auto {% if request.resolver_match.url_name == 'create-account' %}active{% endif %}">
                    <a class="nav-link text-custom-hyperlink" href="{% url 'meetandeat:register' %}">Register{% if request.resolver_match.url_name == 'register' %}<span class="sr-only">(current)</span>{% endif %}</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>


</header>

meeteat/meetandeat/templates/login.html
<!doctype html>
{% load static %}
<html lang="de">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--
    Had to move this from end of body to start of header
    to make 'select2' widget for tags to work
    Maybe there is a better solution but it has to be loaded first
    -->
    <script src="{% static "meetandeat/js/jquery-3.4.1.min.js" %}"></script>

    <link rel="icon" type="image/png" href="{% static "meetandeat/icons_favicon/favicon-32x32.png" %}" sizes="32x32" />
    <link rel="icon" type="image/png" href="{% static "meetandeat/icons_favicon/favicon-16x16.png" %}" sizes="16x16" />
    <link rel="shortcut icon" href="{% static "meetandeat/icons_favicon/favicon.ico" %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">

    <!-- for date and time picker-->
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css"/>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'meetandeat/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'meetandeat/css/global.css' %}">
    <title>Meet and Eat - login</title>
</head>

<body class="bg-custom-primary" id="{{ request.resolver_match.url_name }}">
<div class="d-lg-flex h-md-100 align-items-center">
    <div class="col-md-6 p-0 h-md-100" style="background-color: #dd5549">
        <div class="text-white d-md-flex align-items-center h-100 p-5 text-center justify-content-center">
            <div class="logoarea pt-5 pb-5">
                <p>
                    <i class="fa fa-anchor fa-3x material-icons" style="font-size:48px">fastfood</i>
                </p>
                <h1 class="mb-0 mt-3 display-4">Meet & Eat</h1>
                <h5 class="mb-4 font-weight-light">Meet people and have a nice meal <i
                        class="fab fa-sass fa-2x text-cyan"></i></h5>

            </div>
        </div>
    </div>
    <div class="col-md-6 p-0 bg-white h-md-100 loginarea">
        {% if messages %}
             <div class="m-3 pos-abs-md">
                <ul class="messages">
                    {% for msg in messages %}
                    <li>
                        <div class="alert alert-{{msg.level_tag}}" role="alert">
                            {{msg.message}}
                        </div>
                    </li>
                    {% endfor %}
                </ul>
             </div>
        {% endif %}
        <div class="d-md-flex align-items-center h-md-100 p-5 justify-content-center">

            <form class="border rounded p-5" method="Post">
                {% csrf_token %}
                <h3 class="mb-4 text-center">Sign In</h3>
                <div class="form-group">
                    {{ form.username }}
                </div>
                {% if form.username.errors %}
                    <div class="invalid-feedback">
                        {{ form.username.errors }}
                    </div>
                {% endif %}
                <div class="form-group">
                    {{ form.password }}
                </div>
                {% if form.password.errors %}
                    <div class="invalid-feedback">
                        {{ form.password.errors }}
                    </div>
                {% endif %}
                <button type="submit" class="btn btn-success btn-round btn-block shadow-sm">Sign in</button>
                <small class="d-block mt-4 text-center">
                <span>
                        No account yet? <a class="font-weight-bold" href="{% url 'meetandeat:register' %}">Sign up!</a>
                        </span>
                </small>
                {% if form.non_field_errors %}
                    <div class="border border-danger rounded bg-light p-3 my-4 form-error-login">
                        {% for key, key_errors in form.errors.as_data.items %}
                            {% for error in key_errors %}
                                {% if error.code == 'invalid_login' %}
                                    <p>
                                        Invalid username or password. <br/>Please try again or<br><a
                                            href="{% url 'meetandeat:password-reset-request' %}">reset your
                                        password</a>.
                                    </p>
                                {% endif %}
                            {% endfor %}
                        {% endfor %}
                        {% for key, key_errors in form.errors.as_data.items %}
                            {% for error in key_errors %}
                                {% if error.code == 'inactive' %}
                                    <p>
                                        Your account isn't active <br/>
                                        Please check your email inbox or <br>
                                        <a href="{% url 'meetandeat:request-activation' %}">Request Activation
                                            Link</a>
                                    </p>
                                {% endif %}
                            {% endfor %}
                        {% endfor %}
                    </div>
                {% endif %}
            </form>
        </div>
    </div>
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<!-- jQuery moved to head -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="{% static 'meetandeat/js/bootstrap.js' %}" type="text/javascript"></script>
<script src="{% static 'meetandeat/js/script.js' %}" type="text/javascript"></script>

<!-- for date picker -->
<script type="text/javascript">
    today = new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate());
    $('#id_date').datepicker({
        format: 'dd/mm/yyyy',
        minDate: today
    });
</script>

<!--time picker-->
<script>
    $('#id_time').timepicker({
        mode: '24hr'
    });
</script>

</body>
</html>

meeteat/meetandeat/templates/logout.html
{% extends "base.html" %}
{% block main %}
<div class="container bg-custom-secondary rounded p-3 my-4 text-color-dark text-center" style="max-width: 600px; ">
    <div>
        <h2 class="">Successfully logged out</h2>
        <div style="padding-top: 1em; font-size: 10pt">
            Sign back in? <a href="{% url 'meetandeat:login' %}">Login</a>
        </div>
    </div>
</div>
{% endblock %}