meeteat/meetandeat/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import *

app_name = 'meetandeat'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('event/<int:pk>/', EventDetailView.as_view(), name='event-view'),
    path('event/<int:pk>/join', EventJoinView.as_view(), name='join-event'),
    path('event/<int:pk>/leave', EventLeave.as_view(), name='leave-event'),
    path('event/<int:pk>/report', EventReport.as_view(), name='report-event'),
    path('event/create/', EventCreate.as_view(), name='create-event'),
    path('event/<int:pk>/edit/', EventUpdate.as_view(), name='edit-event'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html',
                                                authentication_form=LoginForm, redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('my_events/', OwnEventsView.as_view(), name='own_events_list'),
    path('profile/edit', UserUpdateView.as_view(), name='edit-profile'),
    path('profile/delete-ajax', UserDeleteAjax.as_view(), name='delete-profile-ajax'),
    path('profile/delete', UserDeleteView.as_view(), name='delete-profile'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('activate_account/<str:uidb64>/<str:token>', UserActivateAccountView.as_view(), name='activate-account'),
    path('request_activation', RequestActivateAccountView.as_view(), name='request-activation'),
    path('request_email_confirm', RequestEmailConfirmView.as_view(), name='request-email-confirm'),
    path('password_reset/request', RequestPasswordResetView.as_view(), name='password-reset-request'),
    path('password_reset/confirm/<str:uidb64>/<str:token>',
         PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('mod/dashboard', ModView.as_view(), name='modView'),
    path('mod/hide/<int:pk>/', ModHide.as_view(), name='modHide'),
    path('mod/unreport/<int:pk>/', ModUnReport.as_view(), name='modUnreport'),
    path('tag/create/', TagCreate.as_view(), name='create-tag'),
    path('mod/tag/<int:pk>/', TagDetailView.as_view(), name='tag-details'),
    path('mod/tag/<int:pk>/edit/', TagUpdate.as_view(), name='edit-tag'),
    path('mod/tag/<int:pk>/approve/', ApproveTag.as_view(), name='approve-tag'),
    path('mod/tag/all/', TagView.as_view(), name='tag-view'),
    path('tags/', NotificationView.as_view(), name='NotificationView'),
    url(r'^ajax/event_get_comments/$', event_get_comments, name='comments_changed'),
]

meeteat/meeteat/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meetandeat.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meeteat/meetandeat/views.py
import json
from datetime import date

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth import update_session_auth_hash, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.db.models import Count, Q
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView, DetailView

from .forms import *
from .helpers import *
from .models import *


class UserIsInGroupMixin(UserPassesTestMixin):
    def test_func(self):
        evt = Event.objects.get(pk=self.kwargs['pk'])
        u = self.request.user
        return u in evt.eventParticipants.all()


class OwnerTestMixin(UserPassesTestMixin):
    def test_func(self):
        evtUser = Event.objects.get(pk=self.kwargs['pk']).user
        ulUser = self.request.user
        print(evtUser, ulUser)
        return evtUser == ulUser


class UserIsStuffMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff


@method_decorator(login_required, name='dispatch')
class IndexView(View):
    def get(self, request, *args, **kwargs):
        form = TagFilterForm()
        ids = Report.objects.filter(reporter=request.user).values_list(
            'event', flat=True).distinct()
        reportedEvents = Event.objects.filter(id__in=ids)

        events = Event.objects.filter(visible=True).difference(
            reportedEvents).order_by('date','time')
        return render(request, 'meetandeat/event_list.html',
                      context={'event_list': events, 'form': form, 'reportedEvents': reportedEvents})

    # Filter Events by Tags
    def post(self, request):
        form = TagFilterForm(request.POST)
        events = Event.objects.filter(visible=True)
        for event in events:
            event.set_matching(101)
        if form.is_valid():
            tags = form.cleaned_data.get('tags')
            idate = form.cleaned_data.get('date')
            time = form.cleaned_data.get('time')
            if tags:
                events = events.filter(tags__in=tags).distinct()
                for event in events:
                    if tags.count() <= event.tags.count():
                        match = 100
                    else:
                        match = event.tags.count() / tags.count() * 100
                    event.set_matching(match)

            if idate:
                events = events.filter(date=idate)
            if time:
                if idate is None:
                    # filter by todays date
                    today = date.today()
                    events = events.filter(date=today)
                # filter by times greater than input time
                events = events.filter(time__gte=time)

            return render(request, 'meetandeat/event_list.html', context={'event_list': events, 'form': form})
        else:
            return render(request, 'meetandeat/event_list.html', context={'event_list': events, 'form': form})


@method_decorator(login_required, name='dispatch')
class EventJoinView(View):
    def get(self, request, *args, **kwargs):
        e = Event.objects.get(id=self.kwargs['pk'])
        u = self.request.user

        # Check if event is already full
        if not e.is_full():
            e.eventParticipants.add(u)

        return redirect('meetandeat:event-view', pk=e.pk)


# TODO: implement template for EventDetailView
@method_decorator(login_required, name='dispatch')
class EventDetailView(UserIsInGroupMixin, DetailView):
    def get(self, request, pk):
        form = CommentForm
        event = get_object_or_404(Event, pk=pk)
        comments = Comment.objects.filter(event=pk)
        return render(request, 'meetandeat/event_details.html',
                      context={'comment_list': comments, 'event': event, 'form': form})

    def post(self, request, pk):
        form = CommentForm(request.POST)
        if form.is_valid():
            print("valid")
            text = form.cleaned_data.get('text')
            author = request.user
            event = get_object_or_404(Event, pk=pk)
            c = Comment(author=author, text=text, event=event)
            c.save()
            return redirect('meetandeat:event-view', pk=pk)


@method_decorator(login_required, name='dispatch')
class EventCreate(CreateView):
    model = Event
    template_name = 'meetandeat/create-event.html'
    form_class = EventForm
    success_url = reverse_lazy('meetandeat:index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class EventUpdate(UpdateView):
    model = Event
    template_name = 'meetandeat/edit-event.html'
    form_class = EventForm
    success_url = reverse_lazy('meetandeat:index')


@method_decorator(login_required, name='dispatch')
class TagView(UserIsStuffMixin, ListView):
    model = Tag


@method_decorator(login_required, name='dispatch')
class TagCreate(CreateView):
    model = Tag
    template_name = 'meetandeat/create-tag.html'
    form_class = TagForm
    success_url = reverse_lazy('meetandeat:NotificationView')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class TagUpdate(UserIsStuffMixin, UpdateView):
    model = Tag
    template_name = 'meetandeat/edit-tag.html'
    form_class = TagDisapprovalForm
    success_url = reverse_lazy('meetandeat:tag-view')

    def form_valid(self, form):
        form.instance.approved = False
        form.instance.pending = False
        form.instance.save()
        return HttpResponseRedirect(self.get_success_url())


@method_decorator(login_required, name='dispatch')
class TagDetailView(UserIsStuffMixin, DetailView):
    model = Tag
    template_name = 'meetandeat/tag_details.html'
    success_url = reverse_lazy('meetandeat:index')


@method_decorator(login_required, name='dispatch')
class EventUpdate(OwnerTestMixin, UpdateView):
    model = Event
    template_name = 'meetandeat/edit-event.html'
    form_class = EventForm
    success_url = reverse_lazy('meetandeat:index')


@method_decorator(login_required, name='dispatch')
class ProfileView(View):
    def get(self, request):
        User = get_user_model()
        user = User.objects.get(pk=request.user.pk)
        context = {
            'user': user,
        }
        return render(request, 'meetandeat/profile.html', context)

    def post(self, request):
        user = request.user
        if 'change-password' in request.POST:
            form = PasswordChangeForm(user=user, data=request.POST)
            if form.is_valid():
                user.set_password(form.cleaned_data['new_password1'])
                user.save()
                update_session_auth_hash(request, user)
                messages.success(request, f'Password was changed')
            else:
                context = {
                    'user': user,
                    'form': form
                }
                return render(request, 'meetandeat/profile.html', context)
        elif 'update-image' in request.POST:
            form = ChangeProfilePictureForm(
                request.POST, request.FILES, instance=user)
            if form.is_valid():
                form.save()
            else:
                context = {
                    'form': form,
                }
                return render(request, 'meetandeat/profile.html', context)

        elif 'delete-image' in request.POST:
            user.profilePicture.delete()
        context = {
            'user': user,
        }
        return render(request, 'meetandeat/profile.html', context)


@method_decorator(login_required, name='dispatch')
class ModView(UserIsStuffMixin, ListView):
    model = Event
    template_name = 'meetandeat/mod_event_list.html'

    def get_queryset(self):
        events = Event.objects.annotate(num_reports=Count('reports', filter=Q(reports__valid=None))).filter(
            num_reports=1)[:5]
        return events


@method_decorator(login_required, name='dispatch')
class ModHide(UserIsStuffMixin, View):
    def post(self, request, pk):
        event = get_object_or_404(Event, pk=pk)
        event.reports.update(valid=True)
        return redirect('meetandeat:modView')


@method_decorator(login_required, name='dispatch')
class ModUnReport(UserIsStuffMixin, View):
    def post(self, request, pk):
        event = get_object_or_404(Event, pk=pk)
        event.reports.update(valid=False)
        event.visible = True
        event.save()
        return redirect('meetandeat:modView')


class UserCreateView(View):
    template_name = 'meetandeat/register.html'

    def get(self, request):
        if request.user.is_authenticated:
            return redirect("meetandeat:profile")
        return render(request, self.template_name)

    def post(self, request):
        if request.user.is_authenticated:
            return redirect("meetandeat:profile")
        form = UserRegistrationForm(request.POST, files=request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.new_activation_attempt()
            user.save()
            sent_emails = send_activation_email(request, user)
            if sent_emails == 0:
                messages.error(request, "Something went wrong, try again")
                user.delete()

meeteat/meetandeat/templates/meetandeat/create-event.html
{% extends 'meetandeat/forms/event-form.html' %}
{% block formTitle %}Create Event{% endblock %}
{% block title %}Create Event{% endblock %}

meeteat/meetandeat/templates/meetandeat/create-tag.html
{% extends 'meetandeat/forms/tag-form.html' %}
{% block formTitle %}Create Tag{% endblock %}
{% block title %}Create Tag{% endblock %}

meeteat/meetandeat/templates/meetandeat/edit-tag.html
{% extends 'meetandeat/forms/tag-disapproval-form.html' %}
{% block formTitle %}Edit Tag{% endblock %}

meeteat/meetandeat/templates/meetandeat/event_details.html
{% extends "base.html" %}
{% load static %}

{% block title %}Event Details{% endblock %}
{% block main %}
<div class="container">
    <div class="row mt-1 pr-3">
        <div class="col text-right">
            <div class="btn-group dropdown">
                <a aria-expanded="false" aria-haspopup="true" class="material-icons md-light btn-custom-dots-dark"
                    data-toggle="dropdown" id="dropdownMenuLink" role="button">
                    more_horiz
                </a>
                <div aria-labelledby="dropdownMenuLink" class="dropdown-menu dropdown-menu-right">
                    {% if event.user == user %}
                    <a class="dropdown-item" href="{% url 'meetandeat:edit-event' event.pk %}">Edit
                        Event</a>
                    {% endif %}
                    {% if user in event.userReportings.all %}
                    <span class="dropdown-item">Already reported!</span>
                    {% else %}
                    <button type="button" class="dropdown-item" data-toggle="modal"
                        data-target="#reportModal">Report</button>
                    {% endif %}
                    {% if user in event.eventParticipants.all %}
                    <a class="dropdown-item" href="{% url 'meetandeat:leave-event' event.pk %}">Leave
                        Event</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="container bg-custom-primary rounded p-3 my-2">
        <div class="row">
            <div class="col" >
                <h2 style="word-wrap: break-word;">{{event.title}} </h2>
            </div>
            <div class="col text-right">
                <div class="btn-group dropdown dropdown-hover dropdown-menu-right">
                    <a aria-expanded="false" aria-haspopup="true" class="md-light" data-toggle="dropdown"
                        id="dropdownMenuLink2" role="button">
                        <small>{{ event.eventParticipants.count }}/{{ event.participants_number }} Participants</small>
                    </a>
                    <div aria-labelledby="dropdownMenuLink2" class="dropdown-menu event-details-participants-dropdown dropdown-menu-hover ">
                        {% for participant in event.eventParticipants.all %}
                        {% if participant == event.user %}
                        <small class="dropdown-item" style="color: #5094ed"><img class="event-details-img"
                                alt="user profile image" {% if participant.profilePicture %}
                                src="{{ participant.profilePicture.url }}"
                                {% else %}src="{% static "meetandeat/img/generic-profile-picture.jpg" %}"
                                {% endif %}> {{ participant.username }}</small>
                        {% elif participant == request.user%}
                        <small class="dropdown-item" style="color: #dc3545"><img class="event-details-img"
                                alt="user profile image" {% if participant.profilePicture %}
                                src="{{ participant.profilePicture.url }}"
                                {% else %}src="{% static "meetandeat/img/generic-profile-picture.jpg" %}"
                                {% endif %}> {{ participant.username }}</small>
                        {% else %}
                        <small class="dropdown-item"><img class="event-details-img" alt="user profile image"
                                {% if participant.profilePicture %} src="{{ participant.profilePicture.url }}"
                                {% else %}src="{% static "meetandeat/img/generic-profile-picture.jpg" %}"
                                {% endif %}> {{ participant.username }} </small>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <small>{{event.description}}</small>
        <div class="spacing"></div>
        <div class="row">
          <div class = "col">
            <small>
              {% for t in event.tags.all %}
              <span class= "container tag-box"> {{t.title}}</span>
              {% endfor %}
            </small>
          </div>
        </div>
        <br>
        <hr>
        <p><span class="material-icons">room</span> {{event.location}}</p>
        <p><span class="material-icons">schedule</span> <span class="pb-1">{{event.date | date:"d.m.Y"}}
                {{ event.time | time:"G:i" }}</span>
        </p>
        <hr>

        <!-- Dynamic loaded -->
        <div id="comment-list"></div>

        <form method='POST' class="border-top pt-4">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    {{form.text}}
                </div>
                <div class="col col-send-comment">
                    <button class="btn btn-custom-primary material-icons" type="submit">send</button>
                </div>
            </div>
        </form>
    </div>
</div>
<form action="{% url 'meetandeat:report-event' event.pk %} " method="post" name="form">
    {% csrf_token %}
    <div aria-hidden="true" aria-labelledby="exampleModalLabel" class="modal fade" id="reportModal" role="dialog"
        tabindex="-1">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Warning</h5>
                    <button aria-label="Close" class="close" data-dismiss="modal" type="button">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to report this event?</p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-custom-secondary" data-dismiss="modal" type="button">Close
                    </button>
                    <input class="btn btn-custom-primary" type="submit" value="Report" />
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

{% block js %}
<script>
    /*
        This script will fetch the latest comments via ajax
        and update the corresponding placeholder
    */
    var comment_html = "";
    function executeQuery() {
        $.ajax({
            url: '/ajax/event_get_comments',
            data: {
                'event_id': '{{ event.id }}',
            },
            dataType: 'json',
            success: function (data) {
                if (comment_html != data.html) {
                    $("#comment-list").html(data.html);
                    comment_html = data.html;
                }
            }
        });
        // refresh every x milliseconds (5s=5000ms)
        setTimeout(executeQuery, 5000);
    }
    $(document).ready(function () {
        executeQuery();
    });
</script>
{% endblock js %}

meeteat/meetandeat/templates/meetandeat/notification_list.html
{% extends "base.html" %}
{% load static %}
{% load tz %}
{% block title %}Tags{% endblock %}
{% block main %}



<div class="container bg-custom-primary rounded p-3 my-4">
  <h3>There is a Tag that you want to have on our site? Submit it now!</h3>
  <a href="{% url 'meetandeat:create-tag' %}" class="btn btn-custom-primary">Submit Tag</a>

{% for tag in tags %}

    {% if tag.approved == False and tag.pending == True %}
    <div class="container bg-custom-secondary rounded  p-3 my-4">
    <p>Your Tag "{{ tag.title }}" is pending.</p>
    </div>
    {% endif %}

    {% if tag.approved == False and tag.pending == False %}
    <div class="container bg-custom-secondary rounded  p-3 my-4">
    <p>Your Tag "{{ tag.title }}" was disapproved because of the following reason: {{ tag.disapprovalMsg }}</p>
    {% if tag.disapprovalMsg == 'Description not clear.' %}
    <p>Description: {{ tag.description }}</p>
    {% endif %}
    </div>
    {% endif %}

    {% if tag.approved == True and tag.pending == False %}
    <div class="container bg-custom-secondary rounded  p-3 my-4">
    <p>Your Tag "{{ tag.title }}" was approved.</p>
    </div>
    {% endif %}

{% endfor %}
</div>

{{ form.media.js }}
{% endblock %}

meeteat/meetandeat/templates/meetandeat/own_events_list.html
{% extends "base.html" %}
{% load static %}
{% load tz %}

{% block title %}Your events{% endblock %}

{% block main %}
<div class="container bg-custom-primary rounded p-3 my-4">
    <h1 class="display-4">My events</h1>


    <!-- Nav tabs -->
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active text-custom-hyperlink" data-toggle="tab" href="#own">Own events</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-custom-hyperlink" data-toggle="tab" href="#joined">Joined events</a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div class="tab-pane container active" id="own">
            {% if own_event_list %}
            {% for event in own_event_list %}
            {% if event.visible == True %}
            <div class="container rounded p-3 my-4 bg-custom-secondary">
    <div class="row">
        <div class="col datefield border-right">
            <div class="container">
                <div class="row"><h3>{{ event.date|  date:"d"}}</h3></div>
                <div class="row border-bottom border-dark" style="margin-top: -8px"><h4>{{ event.date |  date:"M"}}</h4></div>
                <div class="row pt-1">{{ event.time |  date:"G:i"}}</div>
            </div>
        </div>
        <div class="col headline">
            <div class="container">
                <div class="row">
                    <div class="col">
                       {% if user in event.eventParticipants.all %}
                        <h3><a class="text-custom-hyperlink"
                                href="{% url 'meetandeat:event-view' event.pk %}">{{ event.title }}
                                <small>({{ event.eventParticipants.count }}/{{ event.participants_number }})</small></a>
                        </h3>
                        {% else %}
                        <h3>{{ event.title }}
                            <small>({{ event.eventParticipants.count }}/{{ event.participants_number }})</small></h3>
                        {% endif %}
                    </div>
                </div>
                <div class="spacing"></div>
                <div class="row">
                  <div class = "col">
                    <small>
                        {% for t in event.tags.all %}
                        <span class= "container tag-box" > {{t.title}}</span>
                        {% endfor %}
                    </small>
                  </div>
                </div>
                <div class="spacing"></div>
                <div class="spacing"></div>
                <div class="row">
                    <div class="col"><h5><span class="material-icons">room</span>{{ event.location }}</h5></div>
                </div>
            </div>
        </div>
        <div class="col right-col">
            <div class="container">
                <div class="row pl-2">
                    <div class="col">
                        <div class="dropdown">
                            <a aria-expanded="false" aria-haspopup="true" class="material-icons btn-custom-dots"
                               data-toggle="dropdown" id="dropdownMenuLink" role="button">
                                more_horiz
                            </a>
                            <div aria-labelledby="dropdownMenuLink" class="dropdown-menu">
                                {% if event.user == user %}
                                <a class="dropdown-item" href="{% url 'meetandeat:edit-event' event.pk %}">Edit
                                    Event</a>
                                {% endif %}
                                {% if user in event.userReportings.all %}
                                <span class="dropdown-item">Already reported!</span>
                                {% else %}
                                <a class="dropdown-item" href="{% url 'meetandeat:report-event' event.pk %}">Report
                                    Event</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="spacing"></div>
                <div class="spacing"></div>
                <div class="spacing"></div>
                <div class="spacing"></div>
                <div class="row">
                    <div class="col">
                        {% if user in event.eventParticipants.all %}
                        <a class="material-icons btn-custom-leave"
                           href="{% url 'meetandeat:leave-event' event.pk %}">remove</a>
                        {% else %}
                        <a class="material-icons btn-custom-add"
                           href="{% url 'meetandeat:join-event' event.pk %}">add</a>
                        {% endif %}
                    </div>
                </div>
                </div>
            </div>
         </div>
        </div>
            {% endif %}
            {% endfor %}
            {% else %}
            <div class="container border border-dark rounded bg-light p-3 my-4">
                <p>No Results found</p>
            </div>
            {% endif %}
        </div>
        <div class="tab-pane container fade" id="joined">
            {% if joined_event_list %}
            {% for event in joined_event_list %}
            {% if event.visible == True %}
            <div class="container rounded p-3 my-4 bg-custom-secondary">
    <div class="row">
        <div class="col datefield border-right">
            <div class="container">
                <div class="row"><h3>{{ event.date|  date:"d"}}</h3></div>
                <div class="row border-bottom border-dark" style="margin-top: -8px"><h4>{{ event.date |  date:"M"}}</h4></div>
                <div class="row pt-1">{{ event.time |  time:"G:i"}}</div>
            </div>
        </div>
        <div class="col headline">
            <div class="container">
                <div class="row">
                    <div class="col">
                       {% if user in event.eventParticipants.all %}
                        <h3><a class="text-custom-hyperlink"
                                href="{% url 'meetandeat:event-view' event.pk %}">{{ event.title }}
                                <small>({{ event.eventParticipants.count }}/{{ event.participants_number }})</small></a>
                        </h3>
                        {% else %}
                        <h3>{{ event.title }}
                            <small>({{ event.eventParticipants.count }}/{{ event.participants_number }})</small></h3>
                        {% endif %}
                    </div>
                </div>
                <div class="spacing"></div>
                <div class="row">
                  <div class = "col">
                    <small>
                        {% for t in event.tags.all %}
                        <span class= "container tag-box" > {{t.title}}</span>
                        {% endfor %}
                    </small>
                  </div>
                </div>
                <div class="spacing"></div>
                <div class="spacing"></div>
                <div class="row">
                    <div class="col"><h5><span class="material-icons">room</span>{{ event.location }}</h5></div>
                </div>
            </div>
        </div>
        <div class="col right-col">
            <div class="container">
                <div class="row pl-2">
                    <div class="col">
                        <div class="dropdown">
                            <a aria-expanded="false" aria-haspopup="true" class="material-icons btn-custom-dots"
                               data-toggle="dropdown" id="dropdownMenuLink2" role="button">
                                more_horiz
                            </a>
                            <div aria-labelledby="dropdownMenuLink2" class="dropdown-menu">
                                {% if event.user == user %}
                                <a class="dropdown-item" href="{% url 'meetandeat:edit-event' event.pk %}">Edit
                                    Event</a>
                                {% endif %}
                                {% if user in event.userReportings.all %}
                                <span class="dropdown-item">Already reported!</span>
                                {% else %}
                                <a class="dropdown-item" href="{% url 'meetandeat:report-event' event.pk %}">Report
                                    Event</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="spacing"></div>
                <div class="spacing"></div>
                <div class="spacing"></div>
                <div class="spacing"></div>
                <div class="row">
                    <div class="col">
                        {% if user in event.eventParticipants.all %}
                        <a class="material-icons btn-custom-leave"
                           href="{% url 'meetandeat:leave-event' event.pk %}">remove</a>
                        {% else %}
                        <a class="material-icons btn-custom-add"
                           href="{% url 'meetandeat:join-event' event.pk %}">add</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
            {% endif %}
            {% endfor %}
            {% else %}
            <div class="container border border-dark rounded bg-light p-3 my-4">
                <p>No Results found</p>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}